### ISSUE TITLE
Pre-train the BART

### ISSUE THREAD

**Issue by cahya-wirawan** [moussaKam/BARThez#1]
Hi,

Do you have a script to pre-train the BART model? I read your documentation, but I can’t find it. Thanks.

Cahya

**Comment by moussaKam** [comment]
Hi @cahya-wirawan, the pretraining is carried out using [Fairseq](https://github.com/pytorch/fairseq) framework.

Check the [denoising task](https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/denoising.py) that is used to pretrain Bart.
